// Example metadata: names, descriptions, binary paths, and suggested commands.

export const examples = [
  {
    id: "simple",
    name: "Simple",
    description: "Flags, env vars, JSON Schema, MCP",
    binary: "simple.wasm",
    prompt: "myapp",
    suggestions: [
      "--help",
      "-p 9090",
      "--level debug -p 443",
      "--jsonschema",
      "--jsonschema=tree",
    ],
  },
  {
    id: "customtypes",
    name: "Custom Types",
    description: "RegisterType[T], FieldHookProvider, built-in registry",
    binary: "customtypes.wasm",
    prompt: "customtypes",
    suggestions: [
      "serve --help",
      "serve --listen 10.0.0.1:443 --mode prod --timeout 5m",
      "serve --mode dev",
      "serve --mode invalid",
      "serve --listen notahost",
    ],
  },
  {
    id: "structerr",
    name: "Structured Errors",
    description: "Typed errors, validation, semantic exit codes",
    binary: "structerr.wasm",
    prompt: "structerr",
    suggestions: [
      "--help",
      "srv --port 8080",
      "srv --port -1",
      "usr add --email notanemail --age 25 --name John",
      "usr add",
    ],
  },
  {
    id: "full",
    name: "Full",
    description: "All features: debug, jsonschema, validation, presets",
    binary: "full.wasm",
    prompt: "full",
    suggestions: [
      "--help",
      "srv --port 9090 --loglevel debug",
      "--debug-options",
      "--debug-options=json",
      "--jsonschema",
      "usr add",
      "--nonexistent",
    ],
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Simplest possible structcli usage",
    binary: "minimal.wasm",
    prompt: "myapp",
    suggestions: [
      "--help",
      "--port 8080",
      "--loglevel debug --port 443",
    ],
  },
  {
    id: "collections",
    name: "Collections",
    description: "Slices, maps, viper config merging",
    binary: "collections.wasm",
    prompt: "myapp",
    suggestions: [
      "--help",
      "--retries 1,2,3 --backoffs 1s,5s --feature-on true,false --labels env=prod --limits cpu=8 --counts ok=10",
    ],
  },
  {
    id: "loginsvc",
    name: "Login Service",
    description: "Nested subcommands, viper config",
    binary: "loginsvc.wasm",
    prompt: "loginsvc",
    suggestions: [
      "--help",
      "user --help",
      "user add --help",
      "user add -u testuser",
      "user delete --help",
    ],
  },
  {
    id: "mcp-command-factory",
    name: "MCP Command Factory",
    description: "MCP tool discovery + greet subcommand",
    binary: "mcp-command-factory.wasm",
    prompt: "mcp",
    suggestions: [
      "--help",
      "greet --help",
    ],
  },
];
